# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true
exclude: Gemfile, Gemfile.lock, README.md, compass.rb, .gitignore, Rakefile, index.haml

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Colin Bradley
author_email: colinbradley@gmail.com
title: ChickenBootTech
url: http://chickenboot.com/
#url: http://localhost:4000
