# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true
exclude: Gemfile, Gemfile.lock, README.md, compass.rb, .gitignore, Rakefile, index.haml

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Colin Bradley
author_email: colinbradley@gmail.com
title: Mr. Pies' Perambulations
url: http://mrpies.github.com
